### ISSUE TITLE
Provide deployment logic

### ISSUE THREAD

**Issue by LinqLover** [LinqLover/TelegramSmalltalkBot#13]
The following material required for rebuilding the setup of @SqueakSmalltalkBot is currently not publicly available:

- [ ] provisioning script to create a new image and load all dependencies
- [ ] promotion script that installs updates for Trunk + repositories regularly
  * [ ] `Cron` package that schedules this script

(See the wiki for more details of the current set-up)

Questions:

- do we want a 100%-automated solution that can be tested as well?
  * Pro: We could write a CI for it 😋
  * Con: Maybe at least the provisioning script will be never run again
- add these scripts to the current repository or into a separate one?
